"""empty message

Revision ID: bb08bbd03a74
Revises: f7758bca1c91
Create Date: 2022-07-28 22:27:11.243313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb08bbd03a74'
down_revision = 'f7758bca1c91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'public_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('public_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
